local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.find_files, { desc = "Find project files (telescope)"})
vim.keymap.set("n", "<leader-gf>", builtin.git_files, { desc = "Find git files (telescope)" })
vim.keymap.set("n", "<leader>ps", function()
	builtin.grep_string({search = vim.fn.input("Search > ")})
end, { desc = "Find project files (telescope)"})
vim.keymap.set("n", "<leader>pf", builtin.find_files, { desc = "Find project files (telescope)"})
